<?php include __DIR__ . '/../admin-templates/header.php'; ?>

<div class="container px-6 py-8 mx-auto">
  <div class="flex items-center space-x-2 ">
    <h3 class="text-3xl font-medium text-gray-700">Data Barang Habis</h3>
    <a class="cetak-container bg-blue-500 flex text-sm space-x-2 rounded-md px-2 py-1 h-fit text-white hover:blue-700"
      href="/baranghabis/cetak">
      <span class="material-symbols-outlined text-sm">
        print
      </span> <span>Cetak</span>
    </a>
  </div>
  <div class="mt-8">
    <div class="py-2 overflow-x-auto">
      <div class="min-w-full border-b border-gray-200 shadow sm:rounded-lg">
        <table id="barangHabisTable" class="min-w-full divide-y divide-gray-200">
          <thead>
            <tr>
              <th class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Nama
                Barang</th>
              <th class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Tanggal Update Terakhir</th>
            </tr>
          </thead>
          <tbody class="bg-white divide-y divide-gray-200">
            <!-- Table rows will be generated by DataTables -->
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<script>
$(document).ready(function() {
  // Initialize DataTable for Barang Habis
  var tableHabis = $('#barangHabisTable').DataTable({
    ajax: {
      url: '/barang/getbaranghabis', // URL to fetch data from
      dataSrc: '' // Indicates that data is a flat array
    },
    columns: [{
        data: 'nama_barang'
      },
      {
        data: 'updated_at',
        render: function(data, type, row) {
          return formatDateTime(data); // Format date to "12 Januari 2022 Jam 08:00"
        }
      }
    ]
  });

  function formatDateTime(dateTimeString) {
    const dateObj = new Date(dateTimeString);
    const options = {
      day: '2-digit',
      month: 'long',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    };
    return dateObj.toLocaleDateString('id-ID', options);
  }
});
</script>

<?php include __DIR__ . '/../admin-templates/footer.php'; ?>